site_name: CIS-CAT Pro Dashboard Document Library

nav:
    - Home: index.md
    - Source:      
        - 1. Change Log: source/Change Log.md
        - 2. About: source/About Dashboard.md
        - 3. SecureSuite License: source/SecureSuite License.md
        - 4. Installation - Windows: source/Dashboard Deployment Guide for Windows.md
        - 5. Installation - Linux: source/Dashboard Deployment Guide for Linux.md
        - 6. Configuration Options: source/Configuration Options.md
        - 7. Guide: source/Dashboard User's Guide.md
        
theme:
  name: readthedocs